/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + DB connectivity probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates in the authenticated project */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{id}/dynamic-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flat field list for Zapier/Make/n8n integrations
         * @description Returns one field per dynamic field with the flat key format `fields__{name}__{type}`.
         */
        get: operations["getTemplateDynamicFields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listImages"];
        put?: never;
        /**
         * Create an image render
         * @description Cost = 1 credit, or 3 credits for a PDF render (`format=pdf`) or a hi-res output above 3000×3000 px (after `pixel_ratio`). Async by default (returns 202). Pass `?sync=true` to wait up to 30s for the render to complete.
         */
        post: operations["createImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listVideos"];
        put?: never;
        /**
         * Create a video render
         * @description Cost = `ceil(duration_seconds)` credits (1 per second; fps does not affect cost). Async only — completion delivered via webhook subscription.
         */
        post: operations["createVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVideo"];
        put?: never;
        post?: never;
        delete: operations["deleteVideo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBulkJobs"];
        put?: never;
        /** Create a bulk image render job (1-1000 items) */
        post: operations["createBulkImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bulk/{bulk_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBulkJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bulk/{bulk_job_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBulkJobItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhooks"];
        put?: never;
        /**
         * Subscribe to events
         * @description Response includes a one-time `secret` used for HMAC signature verification.
         */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWebhook"];
        put?: never;
        post?: never;
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch: operations["updateWebhook"];
        trace?: never;
    };
    "/v1/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fire a synthetic event to verify the receiver */
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/deliveries/{deliveryId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryWebhookDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description Error category, e.g. "validation_error" */
                type: string;
                /** @description Machine-readable error code */
                code: string;
                message: string;
                /** @description Field path that triggered the error */
                param?: string;
                request_id: string;
            };
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            timestamp: string;
            /** @enum {string} */
            db: "ok" | "error";
        };
        TemplateList: {
            items: {
                id: string;
                /** @enum {string} */
                object: "template";
                project_id: string;
                name: string;
                description: string | null;
                polotno_json?: unknown;
                width: number;
                height: number;
                has_video: boolean;
                default_duration_seconds: string | null;
                default_fps: number | null;
                preview_url: string | null;
                /** Format: date-time */
                preview_generated_at: string | null;
                dynamic_fields: {
                    name: string;
                    /** @enum {string} */
                    type: "text" | "image_url" | "video_url" | "color" | "visibility";
                    /** @enum {string} */
                    element_type: "text" | "image" | "video" | "figure" | "svg";
                    polotno_element_id: string;
                    required?: boolean;
                    default_value?: string | null;
                    description?: string | null;
                    constraints?: {
                        [key: string]: unknown;
                    };
                }[];
                tags: string[];
                archived: boolean;
                self_url: string;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            next_cursor: string | null;
        };
        Template: {
            id: string;
            /** @enum {string} */
            object: "template";
            project_id: string;
            name: string;
            description: string | null;
            polotno_json?: unknown;
            width: number;
            height: number;
            has_video: boolean;
            default_duration_seconds: string | null;
            default_fps: number | null;
            preview_url: string | null;
            /** Format: date-time */
            preview_generated_at: string | null;
            dynamic_fields: {
                name: string;
                /** @enum {string} */
                type: "text" | "image_url" | "video_url" | "color" | "visibility";
                /** @enum {string} */
                element_type: "text" | "image" | "video" | "figure" | "svg";
                polotno_element_id: string;
                required?: boolean;
                default_value?: string | null;
                description?: string | null;
                constraints?: {
                    [key: string]: unknown;
                };
            }[];
            tags: string[];
            archived: boolean;
            self_url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DynamicFields: {
            fields: {
                /** @description Flat key: fields__{name}__{type} */
                key: string;
                label: string;
                /** @enum {string} */
                type: "string" | "url" | "integer" | "color" | "boolean";
                required: boolean;
                help_text?: string;
                default?: string | number | boolean;
            }[];
        };
        Image: {
            id: string;
            /** @enum {string} */
            object: "image";
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed" | "partial";
            template_id: string;
            project_id: string;
            dynamic_fields?: unknown;
            format: string;
            transparent: boolean;
            pixel_ratio: string;
            width: number;
            height: number;
            image_url: string | null;
            webhook_url: string | null;
            metadata?: unknown;
            error?: unknown;
            cost_credits: number;
            estimated_cost_credits: number;
            credits_charged: boolean;
            /** @enum {string} */
            mode: "live" | "test";
            render_duration_ms: number | null;
            self_url: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            submitted_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            expires_at: string;
        };
        ImageCreate: {
            template_id: string;
            /** @default [] */
            dynamic_fields: {
                name: string;
                text?: string;
                /** Format: uri */
                image_url?: string;
                /** Format: uri */
                video_url?: string;
                color?: string;
                font_family?: string;
                font_size?: number;
                visible?: boolean;
            }[];
            /**
             * @default png
             * @enum {string}
             */
            format: "png" | "jpeg" | "pdf";
            /** @default false */
            transparent: boolean;
            /** @default 1 */
            pixel_ratio: number;
            /** Format: uri */
            webhook_url?: string;
            /** @default {} */
            metadata: {
                [key: string]: unknown;
            };
        };
        ImageList: {
            items: {
                id: string;
                /** @enum {string} */
                object: "image";
                /** @enum {string} */
                status: "pending" | "processing" | "completed" | "failed" | "partial";
                template_id: string;
                project_id: string;
                dynamic_fields?: unknown;
                format: string;
                transparent: boolean;
                pixel_ratio: string;
                width: number;
                height: number;
                image_url: string | null;
                webhook_url: string | null;
                metadata?: unknown;
                error?: unknown;
                cost_credits: number;
                estimated_cost_credits: number;
                credits_charged: boolean;
                /** @enum {string} */
                mode: "live" | "test";
                render_duration_ms: number | null;
                self_url: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                submitted_at: string | null;
                /** Format: date-time */
                completed_at: string | null;
                /** Format: date-time */
                expires_at: string;
            }[];
            next_cursor: string | null;
            has_more: boolean;
        };
        Video: {
            id: string;
            /** @enum {string} */
            object: "video";
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed" | "partial";
            template_id: string;
            project_id: string;
            dynamic_fields?: unknown;
            format: string;
            fps: number;
            duration_seconds: string;
            actual_duration_seconds: string | null;
            width: number;
            height: number;
            video_url: string | null;
            thumbnail_url: string | null;
            file_size_bytes: number | null;
            webhook_url: string | null;
            metadata?: unknown;
            error?: unknown;
            cost_credits: number;
            estimated_cost_credits: number;
            credits_charged: boolean;
            /** @enum {string} */
            mode: "live" | "test";
            render_duration_ms: number | null;
            self_url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            submitted_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            /** Format: date-time */
            expires_at: string;
        };
        VideoCreate: {
            template_id: string;
            /** @default [] */
            dynamic_fields: {
                name: string;
                text?: string;
                /** Format: uri */
                image_url?: string;
                /** Format: uri */
                video_url?: string;
                color?: string;
                font_family?: string;
                font_size?: number;
                visible?: boolean;
            }[];
            /**
             * @default mp4
             * @enum {string}
             */
            format: "mp4" | "gif";
            fps?: number;
            duration_seconds?: number;
            /** Format: uri */
            webhook_url?: string;
            /** @default {} */
            metadata: {
                [key: string]: unknown;
            };
        };
        VideoList: {
            items: {
                id: string;
                /** @enum {string} */
                object: "video";
                /** @enum {string} */
                status: "pending" | "processing" | "completed" | "failed" | "partial";
                template_id: string;
                project_id: string;
                dynamic_fields?: unknown;
                format: string;
                fps: number;
                duration_seconds: string;
                actual_duration_seconds: string | null;
                width: number;
                height: number;
                video_url: string | null;
                thumbnail_url: string | null;
                file_size_bytes: number | null;
                webhook_url: string | null;
                metadata?: unknown;
                error?: unknown;
                cost_credits: number;
                estimated_cost_credits: number;
                credits_charged: boolean;
                /** @enum {string} */
                mode: "live" | "test";
                render_duration_ms: number | null;
                self_url: string;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                submitted_at: string | null;
                /** Format: date-time */
                completed_at: string | null;
                /** Format: date-time */
                expires_at: string;
            }[];
            next_cursor: string | null;
            has_more: boolean;
        };
        BulkJob: {
            id: string;
            /** @enum {string} */
            object: "bulk_job";
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed" | "partial";
            template_id: string;
            project_id: string;
            total: number;
            completed: number;
            failed: number;
            format: string;
            pixel_ratio: string;
            estimated_cost_credits: number;
            results_url: string | null;
            webhook_url: string | null;
            metadata?: unknown;
            self_url: string;
            items_url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
        };
        BulkImageCreate: {
            template_id: string;
            items: {
                /** @default [] */
                dynamic_fields: {
                    name: string;
                    text?: string;
                    /** Format: uri */
                    image_url?: string;
                    /** Format: uri */
                    video_url?: string;
                    color?: string;
                    font_family?: string;
                    font_size?: number;
                    visible?: boolean;
                }[];
                /** @default {} */
                metadata: {
                    [key: string]: unknown;
                };
            }[];
            /**
             * @default png
             * @enum {string}
             */
            format: "png" | "jpeg" | "pdf";
            /** @default 1 */
            pixel_ratio: number;
            /** Format: uri */
            webhook_url?: string;
            /** @default {} */
            metadata: {
                [key: string]: unknown;
            };
        };
        BulkJobList: {
            items: {
                id: string;
                /** @enum {string} */
                object: "bulk_job";
                /** @enum {string} */
                status: "pending" | "processing" | "completed" | "failed" | "partial";
                template_id: string;
                project_id: string;
                total: number;
                completed: number;
                failed: number;
                format: string;
                pixel_ratio: string;
                estimated_cost_credits: number;
                results_url: string | null;
                webhook_url: string | null;
                metadata?: unknown;
                self_url: string;
                items_url: string;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                started_at: string | null;
                /** Format: date-time */
                completed_at: string | null;
            }[];
            next_cursor: string | null;
            has_more: boolean;
        };
        BulkJobItemList: {
            items: {
                id: string;
                bulk_job_id: string;
                /** @enum {string} */
                status: "pending" | "processing" | "completed" | "failed" | "partial";
                dynamic_fields?: unknown;
                image_url: string | null;
                metadata?: unknown;
                error?: unknown;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                completed_at: string | null;
            }[];
            next_cursor: string | null;
            has_more: boolean;
        };
        WebhookCreated: {
            id: string;
            project_id: string;
            url: string;
            events: ("image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated")[];
            description: string | null;
            active: boolean;
            /** Format: date-time */
            last_delivery_at: string | null;
            last_delivery_status: number | null;
            consecutive_failures: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            secret: string;
        };
        WebhookCreate: {
            /** Format: uri */
            url: string;
            events: ("image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated")[];
            description?: string;
        };
        WebhookList: {
            items: {
                id: string;
                project_id: string;
                url: string;
                events: ("image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated")[];
                description: string | null;
                active: boolean;
                /** Format: date-time */
                last_delivery_at: string | null;
                last_delivery_status: number | null;
                consecutive_failures: number;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            next_cursor: string | null;
        };
        Webhook: {
            id: string;
            project_id: string;
            url: string;
            events: ("image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated")[];
            description: string | null;
            active: boolean;
            /** Format: date-time */
            last_delivery_at: string | null;
            last_delivery_status: number | null;
            consecutive_failures: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WebhookUpdate: {
            /** Format: uri */
            url?: string;
            events?: ("image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated")[];
            description?: string | null;
            active?: boolean;
        };
        WebhookTestResult: {
            delivery: {
                id: string;
                webhook_id: string | null;
                target_url: string | null;
                event_id: string;
                /** @enum {string} */
                event_type: "image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated";
                payload?: unknown;
                attempt: number;
                /** @enum {string} */
                status: "pending" | "processing" | "success" | "failed" | "dead_letter";
                status_code: number | null;
                response_body: string | null;
                response_headers: {
                    [key: string]: string;
                } | null;
                error_message: string | null;
                duration_ms: number | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                delivered_at: string | null;
                /** Format: date-time */
                next_retry_at: string | null;
            };
            /** @enum {string} */
            status: "success" | "failed";
            status_code: number | null;
        };
        WebhookTestBody: {
            /** @enum {string} */
            event_type: "image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated";
        };
        DeliveryList: {
            items: {
                id: string;
                webhook_id: string | null;
                target_url: string | null;
                event_id: string;
                /** @enum {string} */
                event_type: "image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated";
                payload?: unknown;
                attempt: number;
                /** @enum {string} */
                status: "pending" | "processing" | "success" | "failed" | "dead_letter";
                status_code: number | null;
                response_body: string | null;
                response_headers: {
                    [key: string]: string;
                } | null;
                error_message: string | null;
                duration_ms: number | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                delivered_at: string | null;
                /** Format: date-time */
                next_retry_at: string | null;
            }[];
            next_cursor: string | null;
        };
        Delivery: {
            id: string;
            webhook_id: string | null;
            target_url: string | null;
            event_id: string;
            /** @enum {string} */
            event_type: "image.completed" | "image.failed" | "video.completed" | "video.failed" | "bulk_job.completed" | "bulk_job.item.completed" | "template.created" | "template.updated";
            payload?: unknown;
            attempt: number;
            /** @enum {string} */
            status: "pending" | "processing" | "success" | "failed" | "dead_letter";
            status_code: number | null;
            response_body: string | null;
            response_headers: {
                [key: string]: string;
            } | null;
            error_message: string | null;
            duration_ms: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at: string | null;
            /** Format: date-time */
            next_retry_at: string | null;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Idempotency conflict or duplicate resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded — see Retry-After header */
        RateLimited: {
            headers: {
                /** @description Seconds until retry */
                "Retry-After"?: number;
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                name?: string;
                tag?: string;
                archived?: boolean | null;
                created_after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getTemplateDynamicFields: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DynamicFields"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    listImages: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                template_id?: string;
                status?: "pending" | "processing" | "completed" | "failed" | "partial";
                created_after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    createImage: {
        parameters: {
            query?: {
                sync?: boolean | null;
            };
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageCreate"];
            };
        };
        responses: {
            /** @description Sync completion (only when `?sync=true` and render finishes within 30s) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            /** @description Async — render queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    listVideos: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                template_id?: string;
                status?: "pending" | "processing" | "completed" | "failed" | "partial";
                created_after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    createVideo: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoCreate"];
            };
        };
        responses: {
            /** @description Render queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    listBulkJobs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                status?: "pending" | "processing" | "completed" | "failed" | "partial";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkJobList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    createBulkImages: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkImageCreate"];
            };
        };
        responses: {
            /** @description Bulk job queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getBulkJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bulk_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    listBulkJobItems: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                status?: "pending" | "processing" | "completed" | "failed" | "partial";
            };
            header?: never;
            path: {
                bulk_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkJobItemList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookTestBody"];
            };
        };
        responses: {
            /** @description Synthetic delivery completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookTestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    retryWebhookDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry scheduled */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
}
